//Java Program for Sha
import java.security.*;
import java.io.*;

public class Sha {
    public static String sha(String ip) throws NoSuchAlgorithmException{
        
        MessageDigest md=MessageDigest.getInstance("Sha");
        StringBuffer sb=new StringBuffer();
        byte[] dig=md.digest(ip.getBytes());
        for(int i=0;i<dig.length;i++){
            sb.append(Integer.toString((dig[i]&0xff)+0x100,16).substring(1));
        }
        return sb.toString();
    }
    public static void main(String[] args) throws IOException, NoSuchAlgorithmException {
        BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Enter String: ");
        String inp=br.readLine();
        System.out.println("String: "+inp+"\nDigest: "+sha(inp));
    }
    
}
import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
  
// Java program to calculate MD5 hash value 
public class MD5 { 
    public static String getMd5(String input) 
    { 
        try { 
  
            // Static getInstance method is called with hashing MD5 
            MessageDigest md = MessageDigest.getInstance("MD5"); 
  
            // digest() method is called to calculate message digest 
            //  of an input digest() return array of byte 
            byte[] messageDigest = md.digest(input.getBytes()); 
  
            // Convert byte array into signum representation 
            BigInteger no = new BigInteger(1, messageDigest); 
  
            // Convert message digest into hex value 
            String hashtext = no.toString(16); 
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
            return hashtext; 
        }  
  
        // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) { 
            throw new RuntimeException(e); 
        } 
    } 
  
    // Driver code 
    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
        String s = "GeeksForGeeks"; 
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s)); 
    } 
} 
